# Generated by Django 3.2.16 on 2022-12-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, default='../default_post_of4jmm', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, default='../default_post_of4jmm', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image4',
            field=models.ImageField(blank=True, default='../default_post_of4jmm', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
