# Generated by Django 3.2.16 on 2023-01-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20221228_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='../default_post_of4jmm', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image2',
            field=models.ImageField(default='../default_post_of4jmm', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(default='../default_post_of4jmm', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image4',
            field=models.ImageField(default='../default_post_of4jmm', upload_to='images/'),
        ),
    ]
